#!/bin/bash
echo "Running post-commit hook..."

BRANCH=$(git branch --show-current)
COMMIT=$(git log -1 --pretty=%B)

echo "Successfully committed on branch: $BRANCH"
echo "Commit message: $COMMIT"
exit 0
